### ISSUE TITLE
Tải Douyin 1080p

### ISSUE THREAD

**Issue by merlin7vv4** [TuanThanhDeveloper/DownLoad_All_User_Video_Douyin#4]
Các bác cho em hỏi tải ko login hình như chỉ được 720p thôi phải không ạ

**Comment by huucntt91** [comment]
sao mình chạy mà ko dc nhỉ :(

**Comment by andrewgf988** [comment]
> Các bác cho em hỏi tải ko login hình như chỉ được 720p thôi phải không ạ

tôi cũng k log in, vẫn 1920x1080 mà bạn.

**Comment by andrewgf988** [comment]
> sao mình chạy mà ko dc nhỉ :(

ông dùng notepad+ mở cái main.py ra, rồi làm theo hướng dẫn ý, thay cái link user ở line cuối > save lại rồi run py là đc mà.
